spring.application.name=jazdaz
spring.datasource.url=jdbc:postgresql://localhost:5432/jazdaz
spring.datasource.username=klimient
spring.datasource.password=@Coconut6
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog.xml
gtfs.import.enabled=false
gtfs.import.path=src/main/resources/warsaw_gtfs
spring.config.import=optional:file:.env[.properties]
warsaw.bus-locations.api-key=${WARSAW_API_KEY:}
warsaw.bus-locations.url=https://dane.um.warszawa.pl/api/action/get_ztm_lokalizacja_pojazdow
warsaw.bus-locations.refresh-ms=10000